package barakat.app.repository.mirrorgen;

import barakat.app.model.Catalog;
import barakat.app.view.AppOrdersDetail;
import barakat.tctransport.model.gen.Bkwarehouses;
import org.springframework.data.domain.Page;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 03/06/2022
*/
@Repository
public interface BkwarehousesTcRepository extends JpaRepository<Bkwarehouses, Integer>, JpaSpecificationExecutor<Bkwarehouses> {

    @Query("select new barakat.app.model.Catalog(w.name, w.id) from barakat.app.aggregator.entity.tctransport.model.gen.Bkwarehouses  w where w.customerlink = :customerlink ")
    List<Catalog> findByCustomerlink(Integer customerlink);
}
