package barakat.app.repository.mirrorgen;

import barakat.tctransport.model.gen.Regmoneys;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 03/06/2022
*/
@Repository
public interface RegmoneysTcRepository extends JpaRepository<Regmoneys, Integer>, JpaSpecificationExecutor<Regmoneys> {

}
