jdbcSettings:
  url: "jdbc:firebirdsql://localhost:3050/C:\\etalon\\TSTransport\\TSTRANSPORT.FDB?encoding=UTF8"
  username: "sysdba"
  password: "masterkey"
  driverClassName: "org.firebirdsql.jdbc.FBDriver"

packageName: "barakat.app.aggregator.entity.tctransport.entity.gen"

tableExclusionRules:
  - tableNames: ["FxLogHistory", "FxLogImages", "IBE.*$", "devScripts", "devVersions", "^.*_VIEW"]

interfaceRules:
  # If you just specify the interfaces, all the generated classes'll implement the interfaces.
  - interfaces: [{name: "java.io.Serializable"}]
#
#jpa1SupportRequired: true
#packageNameForJpa1: "tctransport"
