package barakat.app.repository.mirrorgen;

import barakat.tctransport.model.gen.Bkgrants;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 03/06/2022
*/
@Repository
public interface BkgrantsTcRepository extends JpaRepository<Bkgrants, Integer>, JpaSpecificationExecutor<Bkgrants> {

}
