package barakat.app.aggregator.entity.tctransport.repository;

import barakat.app.aggregator.entity.tctransport.model.gen.Eventlog;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 26/05/2022
*/
@Repository
public interface EventlogCustomRepository extends JpaRepository<Eventlog, Integer>, JpaSpecificationExecutor<Eventlog>, CrudRepository<Eventlog, Integer> {

    @Query(value = "select e from barakat.app.aggregator.entity.tctransport.model.gen.Eventlog e where e.id >= :id and e.id < (:id+:count)")
    List<Eventlog> queryById(Integer id, Integer count);
}
