package barakat.app.aggregator.entity.tctransport.repository;

import barakat.app.aggregator.entity.tctransport.model.gen.Wunits;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 26/05/2022
*/
@Repository
public interface WunitsCustomRepository extends JpaRepository<Wunits, Integer>, JpaSpecificationExecutor<Wunits> {
    @Query(value = "select e from barakat.app.aggregator.entity.tctransport.model.gen.Wunits e where e.id >= :id and e.id < (:id+:count)")
    List<Wunits> queryById(Integer id, Integer count);
}
