package barakat.app.repository;

import barakat.app.model.Catalog;
import barakat.tctransport.model.gen.Bkcustomers;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 03/06/2022
*/
@Repository
public interface BkcustomersAppRepository extends JpaRepository<Bkcustomers, Integer>, JpaSpecificationExecutor<Bkcustomers> {

    @Query("select new barakat.app.model.Catalog(c.name, c.id) from barakat.app.aggregator.entity.tctransport.model.gen.Bkcustomers c where lower(c.name)  like %:name% ")
    List<Catalog> findAllByName(String name);
}
