package barakat.app.aggregator.entity.app.cron;

import barakat.app.aggregator.entity.app.CronProperties;
import barakat.app.aggregator.entity.app.CronPropertiesException;
import barakat.app.aggregator.entity.app.TcTransportCopySchedule;
import barakat.app.aggregator.entity.app.repository.mirrorgen.EventlogTcRepository;
import barakat.app.aggregator.entity.tctransport.model.gen.Eventlog;
import barakat.app.aggregator.entity.tctransport.repository.EventlogCustomRepository;
import lombok.extern.log4j.Log4j2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.Scheduled;

import java.util.List;

/**
* Generated by Spring Data Generator on 26/05/2022
*/

@Log4j2
@Configuration
public class EventlogShedule implements TcTransportCopySchedule {
    @Autowired
    EventlogCustomRepository repository;
    @Autowired
    EventlogTcRepository tcRepository;

    private String lastEventId = "eventlog.id.last";

    @Scheduled(fixedDelay = 1000*5)
    private void job() throws CronPropertiesException {
        String id = CronProperties.get(lastEventId);
        if (id == null){
            CronProperties.save(lastEventId, "0");
        }else{
            List<Eventlog>  eventlogs = repository.queryById(Integer.valueOf(id));
            tcRepository.saveAll(eventlogs);
            if(eventlogs.size() != 0){
                CronProperties.save(lastEventId, eventlogs.get(eventlogs.size()-1).getId().toString());
            }
        }
    }
}
