package barakat.app.aggregator.entity.app.cron;

import barakat.app.aggregator.entity.app.TcTransportCopySchedule;
import barakat.app.aggregator.entity.app.repository.mirrorgen.TRepsNumTcRepository;
import barakat.app.aggregator.entity.tctransport.repository.gen.TRepsNumRepository;
import lombok.extern.log4j.Log4j2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

/**
* Generated by Spring Data Generator on 26/05/2022
*/
@Log4j2
@Configuration
public class TRepsNumShedule implements TcTransportCopySchedule {
    @Autowired
    TRepsNumRepository repository;
    @Autowired
    TRepsNumTcRepository tcRepository;

//    @Scheduled(fixedDelay = 1000*60*30)
//    private void job(){
//        log.debug("job synchronise");
//        tcRepository.saveAll(repository.findAll());
//    }
}