package barakat.app.aggregator.entity.app.cron;

import barakat.app.aggregator.entity.app.CronProperties;
import barakat.app.aggregator.entity.app.CronPropertiesException;
import barakat.app.aggregator.entity.app.TcTransportCopySchedule;
import barakat.app.aggregator.entity.app.repository.mirrorgen.WmainTcRepository;
import barakat.app.aggregator.entity.tctransport.model.gen.Wmain;
import barakat.app.aggregator.entity.tctransport.repository.WmainCustomRepository;
import lombok.extern.log4j.Log4j2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.Scheduled;

import java.util.List;

/**
* Generated by Spring Data Generator on 26/05/2022
*/
@Log4j2
@Configuration
public class WmainShedule implements TcTransportCopySchedule {
    @Autowired
    WmainCustomRepository repository;
    @Autowired
    WmainTcRepository tcRepository;

    private String lastQWrecsId = "wmain.id.last";

    @Scheduled(fixedDelay = 1000*60*5)
    private void job() throws CronPropertiesException {

        String id = CronProperties.get(lastQWrecsId);
        if (id == null){
            CronProperties.save(lastQWrecsId, "0");
        }else{
            List<Wmain> eventlogs = repository.queryById(Integer.valueOf(id));
            tcRepository.saveAll(eventlogs);
            if(eventlogs.size() != 0){
                CronProperties.save(lastQWrecsId, eventlogs.get(eventlogs.size()-1).getId().toString());
            }
        }
    }
}