package barakat.app.aggregator.entity.app.cron;

import barakat.app.aggregator.entity.app.CronProperties;
import barakat.app.aggregator.entity.app.CronPropertiesException;
import barakat.app.aggregator.entity.app.TcTransportCopySchedule;
import barakat.app.aggregator.entity.app.repository.mirrorgen.WunitsTcRepository;
import barakat.app.aggregator.entity.tctransport.model.gen.Wunits;
import barakat.app.aggregator.entity.tctransport.repository.WunitsCustomRepository;
import lombok.extern.log4j.Log4j2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.Scheduled;

import java.util.List;

/**
* Generated by Spring Data Generator on 26/05/2022
*/
@Log4j2
@Configuration
public class WunitsShedule implements TcTransportCopySchedule {
    @Autowired
    WunitsCustomRepository repository;
    @Autowired
    WunitsTcRepository tcRepository;

    private String lastWunitsId = "wunits.id.last";

    @Scheduled(fixedDelay = 1000*60)
    private void job() throws CronPropertiesException {
        String id = CronProperties.get(lastWunitsId);
        if (id == null){
            CronProperties.save(lastWunitsId, "0");
        }else{
            List<Wunits> eventlogs = repository.queryById(Integer.valueOf(id));
            tcRepository.saveAll(eventlogs);
            if(eventlogs.size() != 0){
                CronProperties.save(lastWunitsId, eventlogs.get(eventlogs.size()-1).getId().toString());
            }
        }
    }
}