package barakat.tctransport.repository;

import barakat.tctransport.model.gen.Wcargo;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 26/05/2022
*/
@Repository
public interface WcargoCustomRepository extends JpaRepository<Wcargo, Integer>, JpaSpecificationExecutor<Wcargo> {
    @Query(value = "select e from barakat.app.aggregator.entity.tctransport.model.gen.Wcargo e where e.id >= :id and e.id < (:id+:count)")
    List<Wcargo> queryById(Integer id, Integer count);
}
